version: "3.3"

services:
  frontend:
    build:
      dockerfile: docker/dev/frontend.Dockerfile
      context: ../..
    image: threatpulse-frontend
    container_name: threatpulse-frontend
    hostname: frontend
    tty: true
    ports:
      - 8001:8001
    volumes:
      - ../../frontend/:/app:rw
    command: >
      bash -c "/tmp/venv/bin/uvicorn "back_simulation.main:app" --host 0.0.0.0 --port 8002 & (npm install && npm run dev)"


  backend:
    build:
      dockerfile: docker/dev/backend.Dockerfile
      context: ../..
    image: threatpulse-backend
    container_name: threatpulse-backend
    hostname: backend
    tty: true
    ports:
      - 1234:1234
    volumes:
      - ../../backend:/app:rw
    command: >
      bash -c "poetry install && poetry run threatpulse serve" 